controllers/BackendController.php
<?php

namespace app\controllers;

use app\components\Calculator;
use app\models\Result;
use DateTime;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\ServerErrorHttpException;

class BackendController extends Controller {
  /**
   * {@inheritdoc}
   */
  public function behaviors() {
    return [
      'access' => [
        'class' => AccessControl::class,
        'rules' => [
          [
            'allow' => TRUE,
            'roles' => ['@'],
          ],
        ],
      ],
    ];
  }

  /**
   * Список групп
   * @param bool $finished
   * @return string
   * @throws \Exception
   */
  public function actionIndex($finished = false) {
    $groups = Yii::$app->holyhope->getGroups($finished);

    return $this->render('index', [
      'groups' => $groups,
      'finished' => !!$finished,
    ]);
  }

  /**
   * Форма подсчёта
   * @param $id
   * @param null $calculator
   * @return string
   * @throws \ReflectionException
   * @throws \yii\web\NotFoundHttpException
   * @throws \Exception
   */
  public function actionGroup($id, $calculator = NULL) {
    $group = Yii::$app->holyhope->getGroup($id);

    if (!$group) {
      throw new NotFoundHttpException('Group is not found on Holyhope');
    }

    $students = Yii::$app->holyhope->getGroupStudents($id);

    $calculators = Calculator::calculators();

    if ($calculator) {
      if (!array_key_exists($calculator, $calculators)) {
        throw new NotFoundHttpException();
      }

      Yii::$app->view->params['back'] = ['backend/group', 'id' => $id];

      /** @var Calculator|string $calculator */
      $calculator = $calculators[$calculator];

      // Сохраняем результаты

      if (Yii::$app->request->isPost && Yii::$app->request->post('students')) {
        $result = $calculator->submit(Yii::$app->request->post(), $group);
        Yii::$app->session->addFlash('success', 'Form has been submitted, thank you!');
        return $this->redirect(['backend/result', 'id' => $result->id]);
      }

      // Начало и конец обучения

      $replace = function ($value) {
        return preg_replace('~^(\d\d)\.(\d\d)\.(\d{4})$~', '$3-$2-$1', $value);
      };

      $group['_start_date'] = min(array_map($replace, array_filter(array_column($group['ScheduleItems'] ?? [], 'BeginDate'))));
      $group['_end_date'] = max(array_map($replace, array_filter(array_column($group['ScheduleItems'] ?? [], 'EndDate'))));

      // Студенты

      $students = array_map(function ($student) {
        $student['_student'] = Yii::$app->holyhope->getStudent($student['StudentId']);
        $student['_age'] = (new DateTime(ArrayHelper::getValue($student['_student'], 'Birthday', date('c'))))->diff(new DateTime('now'))->y;
        return $student;
      }, $students);

      return $this->render('calculators/' . $calculator->getView(), [
        'group' => $group,
        'students' => $students,
        'calculator' => $calculator,
      ]);
    }

    Yii::$app->view->params['back'] = ['backend/index'];

    /** @var Result[] $results */
    $results = Result::find()->where(['group_id' => $id])->orderBy(['created_at' => SORT_DESC])->all();

    return $this->render('group', [
      'group' => $group,
      'students' => $students,
      'calculators' => $calculators,
      'results' => $results,
    ]);
  }

  /**
   * Результаты формулы и генерация сертификатов
   * @param $id
   * @throws \yii\web\NotFoundHttpException
   */
  public function actionResult($id) {
    $result = Result::findOne($id);

    if (!$result) {
      throw new NotFoundHttpException('Results not found in database');
    }

    if (!$result->group_id) {
      throw new ServerErrorHttpException('Group ID is not defined');
    }

    $group = Yii::$app->holyhope->getGroup($result->group_id);

    if (!$group) {
      throw new NotFoundHttpException('Group is not found on Holyhope');
    }

    Yii::$app->view->params['back'] = ['backend/group', 'id' => $result->group_id];

    if (Yii::$app->request->isPost && Yii::$app->request->post('students')) {
      $r = Yii::$app->request;

      $zip = $result->generateCertificates($r->post('students'), $r->post('course'), $r->post('tutor'), $r->post('assistant'), $r->post('position'), $r->post('certificate_level'));

      return Yii::$app->response->sendFile($zip);
    }

    return $this->render('result', [
      'result' => $result,
      'group' => $group,
    ]);
  }

  /**
   * @param $id
   * @return \yii\console\Response|\yii\web\Response
   * @throws \yii\web\NotFoundHttpException
   */
  public function actionDownloadResult($id) {
    $result = Result::findOne($id);

    if (!$result) {
      throw new NotFoundHttpException('Results not found in database');
    }

    if (!$result->pdf_path) {
      throw new NotFoundHttpException('Results file not found');
    }

    return Yii::$app->response->sendFile(Yii::getAlias('@files') . '/' . $result->pdf_path);
  }

  public function actionResults() {
    if (!Yii::$app->helper->isAdmin()) {
      throw new ForbiddenHttpException();
    }

    $results = Result::find()->orderBy(['created_at' => SORT_DESC])->all();

    return $this->render('results', [
      'results' => $results,
    ]);
  }
}

views/layouts/login.php
<?php

/**
 * @var $this \yii\web\View
 * @var $content string
 */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\helpers\Html;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?php echo Yii::$app->language; ?>">
<head>
  <meta charset="<?php echo Yii::$app->charset; ?>">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <?php $this->registerCsrfMetaTags() ?>
  <title><?php echo Html::encode($this->title); ?></title>
  <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
  <div class="container">
    <?php echo Alert::widget(); ?>
    <?php echo $content; ?>
  </div>
</div>

<?php $this->endBody(); ?>
</body>
</html>
<?php $this->endPage(); ?>

views/layouts/main.php
<?php

/**
 * @var $this \yii\web\View
 * @var $content string
 */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\helpers\Html;
use yii\helpers\Url;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?php echo Yii::$app->language; ?>">
<head>
  <meta charset="<?php echo Yii::$app->charset; ?>">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <?php $this->registerCsrfMetaTags() ?>
  <title><?php echo Html::encode($this->title); ?></title>
  <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
  <header class="d-flex align-items-center">
    <div class="container d-flex align-items-center">
      <div class="d-flex align-items-center w-100">
        <?php if (!empty($this->params['back'])): ?>
          <div class="nav-buttons mr-5">
            <?php echo Html::a('<i class="fas fa-arrow-left"></i>', $this->params['back'], ['class' => 'back btn btn-link']); ?>

            <?php if ($this->params['back'] !== ['backend/index']): ?>
              <?php echo Html::a('<i class="fas fa-home"></i>', ['backend/index'], ['class' => 'up btn btn-link']); ?>
            <?php endif; ?>
          </div>
        <?php endif; ?>

        <div class="logo">
          <a href="<?php echo Url::to(['backend/index']) ?>"><img src="/images/logo.png" alt="" class="img-fluid" /></a>
        </div>

        <?php if (Yii::$app->helper->isAdmin()): ?>
          <div class="nav-buttons ml-auto">
            <?php echo Html::a('<i class="fas fa-list"></i>', ['backend/results'], ['class' => 'back btn btn-link']); ?>
          </div>
        <?php endif; ?>

        <?php echo Html::beginForm(['/site/logout'], 'post', ['class' => Yii::$app->helper->isAdmin() ? 'ml-1' : 'ml-auto']) . Html::submitButton('Logout <i class="fa fa-sign-out-alt"></i>', ['class' => 'btn btn-link logout']) . Html::endForm() ?>
      </div>
    </div>
  </header>

  <div class="content">
    <div class="container">
      <?php echo Alert::widget(); ?>
      <?php echo $content; ?>
    </div>
  </div>
</div>

<?php $this->endBody(); ?>
</body>
</html>
<?php $this->endPage(); ?>