controllers/BackendController.php
<?php

namespace app\controllers;

use app\components\Calculator;
use app\models\Result;
use DateTime;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\ServerErrorHttpException;

class BackendController extends Controller {
  /**
   * {@inheritdoc}
   */
  public function behaviors() {
    return [
      'access' => [
        'class' => AccessControl::class,
        'rules' => [
          [
            'allow' => TRUE,
            'roles' => ['@'],
          ],
        ],
      ],
    ];
  }

  /**
   * Список групп
   * @param bool $finished
   * @return string
   * @throws \Exception
   */
  public function actionIndex($finished = false) {
    $groups = Yii::$app->holyhope->getGroups($finished);

    return $this->render('index', [
      'groups' => $groups,
      'finished' => !!$finished,
    ]);
  }

  /**
   * Форма подсчёта
   * @param $id
   * @param null $calculator
   * @return string
   * @throws \ReflectionException
   * @throws \yii\web\NotFoundHttpException
   * @throws \Exception
   */
  public function actionGroup($id, $calculator = NULL) {
    $group = Yii::$app->holyhope->getGroup($id);

    if (!$group) {
      throw new NotFoundHttpException('Group is not found on Holyhope');
    }

    $students = Yii::$app->holyhope->getGroupStudents($id);

    $calculators = Calculator::calculators();

    if ($calculator) {
      if (!array_key_exists($calculator, $calculators)) {
        throw new NotFoundHttpException();
      }

      Yii::$app->view->params['back'] = ['backend/group', 'id' => $id];

      /** @var Calculator|string $calculator */
      $calculator = $calculators[$calculator];

      // Сохраняем результаты

      if (Yii::$app->request->isPost && Yii::$app->request->post('students')) {
        $result = $calculator->submit(Yii::$app->request->post(), $group);
        Yii::$app->session->addFlash('success', 'Form has been submitted, thank you!');
        return $this->redirect(['backend/result', 'id' => $result->id]);
      }

      // Начало и конец обучения

      $replace = function ($value) {
        return preg_replace('~^(\d\d)\.(\d\d)\.(\d{4})$~', '$3-$2-$1', $value);
      };

      $group['_start_date'] = min(array_map($replace, array_filter(array_column($group['ScheduleItems'] ?? [], 'BeginDate'))));
      $group['_end_date'] = max(array_map($replace, array_filter(array_column($group['ScheduleItems'] ?? [], 'EndDate'))));

      // Студенты

      $students = array_map(function ($student) {
        $student['_student'] = Yii::$app->holyhope->getStudent($student['StudentId']);
        $student['_age'] = (new DateTime(ArrayHelper::getValue($student['_student'], 'Birthday', date('c'))))->diff(new DateTime('now'))->y;
        return $student;
      }, $students);

      return $this->render('calculators/' . $calculator->getView(), [
        'group' => $group,
        'students' => $students,
        'calculator' => $calculator,
      ]);
    }

    Yii::$app->view->params['back'] = ['backend/index'];

    /** @var Result[] $results */
    $results = Result::find()->where(['group_id' => $id])->orderBy(['created_at' => SORT_DESC])->all();

    return $this->render('group', [
      'group' => $group,
      'students' => $students,
      'calculators' => $calculators,
      'results' => $results,
    ]);
  }

  /**
   * Результаты формулы и генерация сертификатов
   * @param $id
   * @throws \yii\web\NotFoundHttpException
   */
  public function actionResult($id) {
    $result = Result::findOne($id);

    if (!$result) {
      throw new NotFoundHttpException('Results not found in database');
    }

    if (!$result->group_id) {
      throw new ServerErrorHttpException('Group ID is not defined');
    }

    $group = Yii::$app->holyhope->getGroup($result->group_id);

    if (!$group) {
      throw new NotFoundHttpException('Group is not found on Holyhope');
    }

    Yii::$app->view->params['back'] = ['backend/group', 'id' => $result->group_id];

    if (Yii::$app->request->isPost && Yii::$app->request->post('students')) {
      $r = Yii::$app->request;

      $zip = $result->generateCertificates($r->post('students'), $r->post('course'), $r->post('tutor'), $r->post('assistant'), $r->post('position'), $r->post('certificate_level'));

      return Yii::$app->response->sendFile($zip);
    }

    return $this->render('result', [
      'result' => $result,
      'group' => $group,
    ]);
  }

  /**
   * @param $id
   * @return \yii\console\Response|\yii\web\Response
   * @throws \yii\web\NotFoundHttpException
   */
  public function actionDownloadResult($id) {
    $result = Result::findOne($id);

    if (!$result) {
      throw new NotFoundHttpException('Results not found in database');
    }

    if (!$result->pdf_path) {
      throw new NotFoundHttpException('Results file not found');
    }

    return Yii::$app->response->sendFile(Yii::getAlias('@files') . '/' . $result->pdf_path);
  }

  public function actionResults() {
    if (!Yii::$app->helper->isAdmin()) {
      throw new ForbiddenHttpException();
    }

    $results = Result::find()->orderBy(['created_at' => SORT_DESC])->all();

    return $this->render('results', [
      'results' => $results,
    ]);
  }
}

views/backend/_group-info.php
<?php

/**
 * @var $this \yii\web\View
 * @var $group array
 */

use yii\helpers\Html;

?>

<?php if ($group): ?>
  <article>
    <h3><?php echo Html::encode($group['Name'] ?? '—'); ?></h3>
    <div class="row">
      <div class="col-lg-6">
        <table class="table">
          <tbody>
          <tr>
            <th>School</th>
            <td><?php echo Html::encode($group['School'] ?? '—'); ?></td>
          </tr>
          <tr>
            <th>Discipline</th>
            <td><?php echo Html::encode($group['Discipline'] ?? '—'); ?></td>
          </tr>
          <tr>
            <th>Level</th>
            <td><?php echo Html::encode($group['Level'] ?? '—'); ?></td>
          </tr>
          <tr>
            <th>Maturity</th>
            <td><?php echo Html::encode($group['Maturity'] ?? '—'); ?></td>
          </tr>
          <tr>
            <th>Learning Type</th>
            <td><?php echo Html::encode($group['LearningType'] ?? '—'); ?></td>
          </tr>
          </tbody>
        </table>
      </div>

      <?php if (!empty($this->blocks['results'])): ?>
        <div class="col-lg-6">
          <?php echo $this->blocks['results']; ?>
        </div>
      <?php endif; ?>
    </div>
  </article>
<?php endif; ?>

views/backend/group.php
<?php

/**
 * @var $this \yii\web\View
 * @var $group array
 * @var $students array
 * @var $calculators \app\components\Calculator[]
 * @var $results \app\models\Result[]
 */

use yii\helpers\Html;

$this->title = 'Group ' . ($group['Name'] ?? '???');

?>

<?php if ($results): ?>
  <?php $this->beginBlock('results'); ?>

  <h4>Previous results</h4>
  <ul>
    <?php foreach ($results as $result): ?>
      <li>
        <?php echo Html::a(Yii::$app->formatter->asDatetime($result->created_at) . ' - ' . Html::encode($result->calculator()->getLevel(TRUE) ?? $result->level), [
          'backend/result',
          'id' => $result->id,
        ]); ?>
      </li>
    <?php endforeach; ?>
  </ul>

  <?php $this->endBlock(); ?>
<?php endif; ?>

<?php //----------------------------------- ?>

<?php echo $this->render('_group-info', ['group' => $group]); ?>

<?php if ($calculators): ?>
  <article>
    <h3>Choose the formula</h3>

    <ul>
      <?php if (strtolower($group['Maturity'] ?? NULL) === 'kids'): ?>
        <li>
          <strong><?php echo Html::a('Kids', ['backend/group', 'id' => $group['Id'], 'calculator' => 'kids']); ?></strong>
        </li>
      <?php endif; ?>

      <?php foreach ($calculators as $slug => $calculator): ?>
        <li>
          <?php echo Html::a($calculator->getLevel(TRUE), ['backend/group', 'id' => $group['Id'], 'calculator' => $slug]); ?>
        </li>
      <?php endforeach; ?>
    </ul>
  </article>
<?php endif; ?>

<article>
  <?php if ($students): ?>
    <h3>Students</h3>
    <div class="table-responsive">
      <table class="table" data-toggle="table" data-search="true" data-search-align="left" data-trim-on-search="false" data-search-time-out="400" data-custom-search="customSearch" data-sort-name="0">
        <thead>
        <tr>
          <th data-sortable="true">Name</th>
          <th data-sortable="true">Transliterated Name</th>
          <th data-sortable="true">Begin Date</th>
          <th data-sortable="true">End Date</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($students as $student): ?>
          <tr>
            <td><?php echo Html::encode($student['StudentName'] ?? '—'); ?></td>
            <td><?php echo Html::encode($student['_transliterated_name'] ?? '—'); ?></td>
            <td><?php echo Html::encode($student['BeginDate'] ?? '—'); ?></td>
            <td><?php echo Html::encode($student['EndDate'] ?? '—'); ?></td>
          </tr>
        <?php endforeach; ?>
        </tbody>
      </table>
    </div>
  <?php else: ?>
    <em>Students list is empty</em>
  <?php endif; ?>
</article>

views/backend/index.php
<?php

/**
 * @var $this \yii\web\View
 * @var $groups array
 * @var $finished bool
 */

use yii\helpers\Html;

$this->title = 'Groups';

?>

<?php if ($groups): ?>
  <h3>Choose a Group</h3>

  <?php echo yii\bootstrap4\Tabs::widget([
    'items' => [
      [
        'label' => 'Active',
        'url' => ['backend/index'],
        'active' => !$finished,
      ],
      [
        'label' => 'Finished',
        'url' => ['backend/index', 'finished' => 'yes'],
        'active' => $finished,
      ],
    ],
  ]); ?>

  <div class="table-responsive">
    <table class="table" data-toggle="table" data-search="true" data-search-align="left" data-trim-on-search="false" data-search-time-out="400" data-custom-search="customSearch">
      <thead>
      <tr>
        <th data-sortable="true">Group</th>
        <th data-sortable="true">School</th>
        <th data-sortable="true" data-searchable="false">Discipline</th>
        <th data-sortable="true">Level</th>
        <th data-sortable="true">Maturity</th>
        <th data-sortable="true">Learning Type</th>
      </tr>
      </thead>
      <tbody>
      <?php foreach ($groups as $group): ?>
        <tr>
          <td>
            <span hidden>
              <?php echo Html::encode(preg_replace_callback('~^(\d+)~', function ($match) {
                return str_pad($match[1], 10, 0, STR_PAD_LEFT);
              }, $group['Name'] ?? '—')); ?>
            </span>
            <?php echo Html::a(Html::encode($group['Name'] ?? '—'), ['backend/group', 'id' => $group['Id']]); ?>
          </td>
          <td><?php echo Html::encode($group['School'] ?? '—'); ?></td>
          <td><?php echo Html::encode($group['Discipline'] ?? '—'); ?></td>
          <td><?php echo Html::encode($group['Level'] ?? '—'); ?></td>
          <td><?php echo Html::encode($group['Maturity'] ?? '—'); ?></td>
          <td><?php echo Html::encode($group['LearningType'] ?? '—'); ?></td>
        </tr>
      <?php endforeach; ?>
      </tbody>
    </table>

  </div>
<?php else: ?>
  <em>Groups list is empty</em>
<?php endif; ?>

views/backend/result.php
<?php

/**
 * @var $this \yii\web\View
 * @var $group array
 * @var $result \app\models\Result
 */

use yii\helpers\Html;

$this->title = 'Group ' . $group['Name'] ?? '???';

$courses = [
  'English for Kids',
  'General English',
  'English for Teens',
];

$positions = [
  'Director of Studies',
  'Assistant Director Of Studies',
  'Senior Teacher',
];

?>


<?php $this->beginBlock('results'); ?>
  <h4>Download results</h4>
  <ul>
    <li>
      <?php echo Html::a(Html::encode(basename($result->pdf_path)), ['backend/download-result', 'id' => $result->id]); ?>
    </li>
  </ul>
<?php $this->endBlock(); ?>

<?php //----------------------------------- ?>


<?php echo $this->render('_group-info', ['group' => $group]); ?>

<?php echo Html::beginForm('', 'post', ['data-dos-duration' => 5000]); ?>

<?php echo Html::hiddenInput('group_id', $group['Id']); ?>
  <h3>Certificates</h3>

  <div class="table-responsive">
    <table class="table">
      <tr>
        <th>Class number</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Book used</th>
        <th>Level</th>
      </tr>
      <tr>
        <td><?php echo Html::encode($result->class_number); ?></td>
        <td><?php echo Html::encode($result->start_date); ?></td>
        <td><?php echo Html::encode($result->end_date); ?></td>
        <td><?php echo Html::encode($result->book); ?></td>
        <td><?php echo Html::encode($result->level); ?></td>
      </tr>
    </table>
  </div>

  <!--<div class="form-group">
    <label for="course">Course: (Please make sure the correct course is specified)</label>
    <?php /*echo Html::textInput('course', !empty($group['LearningType']) ? $group['LearningType'] : $result->book, [
      'id' => 'course',
      'class' => 'form-control',
      'required' => TRUE,
    ]); */ ?>
  </div>-->

  <div class="form-group">
    <label for="course">Course:</label>
    <?php echo Html::dropDownList('course', $group['LearningType'] ?? NULL, array_combine($courses, $courses), ['id' => 'position', 'class' => 'form-control', 'required' => TRUE, 'prompt' => '']); ?>
  </div>

  <div class="form-group">
    <label for="certificate-level">Certificate Level:</label>
    <?php echo Html::textInput('certificate_level', $result->calculator()->getCertificateLevel(), [
      'id' => 'certificate-level',
      'class' => 'form-control',
      'required' => TRUE,
    ]); ?>
  </div>

  <div class="form-group">
    <label for="tutor">Course Tutor:</label>
    <?php echo Html::textInput('tutor', '', ['id' => 'tutor', 'class' => 'form-control', 'required' => TRUE]); ?>
  </div>

  <div class="form-group">
    <label for="position">Please choose the position of your line manager:</label>
    <?php echo Html::dropDownList('position', 'Assistant Director Of Studies', array_combine($positions, $positions), ['id' => 'position', 'class' => 'form-control', 'required' => TRUE]); ?>
  </div>

  <div class="form-group">
    <label for="assistant">Please type in their name:</label>
    <?php echo Html::textInput('assistant', '', ['id' => 'assistant', 'class' => 'form-control', 'required' => TRUE]); ?>
  </div>

  <h3 class="mt-5 mb-3">Students</h3>

  <div class="table-responsive">
    <table class="table table-sm mx-auto w-auto" style="max-width: 1600px;">
      <thead>
      <tr>
        <th style="width: 1%;"></th>
        <th>Name</th>
        <th>Transliterated Name</th>
        <th style="width: 190px;">Start Date</th>
        <th style="width: 190px;">End Date</th>
        <th>Result</th>
      </tr>
      </thead>
      <tbody>
      <?php foreach ($result->students as $index => $student): $_result = $result->getResult($index); ?>
        <tr>
          <td><?php echo $index + 1; ?></td>
          <td><?php echo Html::encode($result->getName($index)); ?></td>
          <td>
            <?php echo Html::textInput("students[{$index}][name]", Yii::$app->helper->transliterate($result->getName($index, TRUE)), [
              'class' => 'form-control form-control-sm',
              'required' => TRUE,
            ]); ?>
          </td>
          <td>
            <?php echo Html::textInput("students[{$index}][start_date]", $student['_start_date'] ?? NULL, [
              'class' => 'form-control form-control-sm',
              'type' => 'date',
              'required' => TRUE,
            ]); ?>
          </td>
          <td>
            <?php echo Html::textInput("students[{$index}][end_date]", $student['_end_date'] ?? NULL, [
              'class' => 'form-control form-control-sm',
              'type' => 'date',
              'required' => TRUE,
            ]); ?>
          </td>
          <td>
            <label class="form-check-label w-100">
              <?php echo Html::checkbox("students[{$index}][enable]", $_result && $_result !== 'Fail'); ?>
              <?php echo Html::hiddenInput("students[{$index}][result]", $_result); ?>
              <?php echo Html::encode($_result); ?>
            </label>
          </td>
        </tr>
      <?php endforeach; ?>
      </tbody>
    </table>
  </div>


<?php echo Html::submitButton('Download certificates', ['class' => 'btn btn-primary']); ?>
<?php echo Html::endForm(); ?>

views/backend/results.php
<?php

/**
 * @var $this \yii\web\View
 * @var $results \app\models\Result[]
 */

use yii\helpers\Html;

$this->title = 'Results';

?>

<?php if ($results): ?>
  <h3>Results</h3>

  <div class="table-responsive">
    <table class="table" data-toggle="table" data-search="true" data-search-align="left" data-trim-on-search="false" data-search-time-out="400" data-custom-search="customSearch">
      <thead>
      <tr>
        <th data-sortable="true">Class Number</th>
        <th data-sortable="true">Formula</th>
        <th data-sortable="true">Level</th>
        <th data-sortable="true">Book</th>
        <th data-sortable="true">Start Date</th>
        <th data-sortable="true">End Date</th>
        <th data-sortable="true">Created</th>
      </tr>
      </thead>
      <tbody>
      <?php foreach ($results as $result): ?>
        <tr>
          <td>
            <span hidden>
              <?php echo Html::encode(preg_replace_callback('~^(\d+)~', function ($match) {
                return str_pad($match[1], 10, 0, STR_PAD_LEFT);
              }, $result->class_number)); ?>
            </span>
            <?php echo Html::a(Html::encode($result->class_number), ['backend/result', 'id' => $result->id]); ?>
          </td>
          <td><?php echo Html::encode($result->calculator()->getLevel(TRUE) ?? '—'); ?></td>
          <td><?php echo Html::encode($result->level); ?></td>
          <td><?php echo Html::encode($result->book); ?></td>
          <td><?php echo Html::encode($result->start_date); ?></td>
          <td><?php echo Html::encode($result->end_date); ?></td>
          <td><?php echo Yii::$app->formatter->asDatetime($result->created_at, 'php:Y-m-d H:i'); ?></td>
        </tr>
      <?php endforeach; ?>
      </tbody>
    </table>

  </div>
<?php else: ?>
  <em>Groups list is empty</em>
<?php endif; ?>